# Cada servicio declarado corresponde a un contenedor
# docker run -d -p 5000:5000 --name 09-pokeapi pokeapi:0.0.1 

#Revisar esta documentación https://levelup.gitconnected.com/how-to-access-a-docker-container-from-another-container-656398c93576
version: '3'
services:
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    image: 191006/ms-frontend:1.0
    #añade entradas al archivo /etc/hosts
    extra_hosts:
      - "products:172.25.0.10"
      - "shopping-cart:172.25.0.20"
    # Importante dejar las variables como valores y no como string de datos, es decir entre comillas, sino entrega error 'getaddrinfo ENOTFOUND "172.25.0.10"'
    environment:
      - PRODUCTS_SERVICE=products
      - SHOPPING_CART_SERVICE=shopping-cart
    networks:
      bootcampfinal:
        ipv4_address: 172.25.0.5

  shopping-cart:
    container_name: shopping-cart
    ports:
     - "3001:3001"
    image: 191006/ms-shopping-cart:1.0
    networks:
      bootcampfinal:
        ipv4_address: 172.25.0.20

  products:
    container_name: products
    ports:
     - "3002:3002"
    image: 191006/ms-products:1.0
    networks:
      bootcampfinal:
        ipv4_address: 172.25.0.10

networks:
  bootcampfinal:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1
